# Generated by Django 5.2.4 on 2025-07-14 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amuleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='amuletos/')),
                ('efeito', models.TextField()),
                ('custo', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='chefes/')),
                ('info_chefe', models.TextField()),
                ('skills', models.TextField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='feiticos/')),
                ('efeito', models.TextField()),
                ('custo', models.CharField(max_length=50)),
                ('localizacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mascara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='mascaras/')),
                ('fragmentos_necessarios', models.PositiveIntegerField()),
                ('aumenta_vida', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='npcs/')),
                ('funcao', models.TextField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaleOre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pale_ores/')),
            ],
        ),
        migrations.CreateModel(
            name='Recipiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='recipientes/')),
                ('fragmentos_necessarios', models.PositiveIntegerField()),
                ('soul', models.PositiveIntegerField(help_text='Quantidade de alma que esse recipiente fornece')),
            ],
        ),
        migrations.CreateModel(
            name='Exploracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('chefes', models.ManyToManyField(blank=True, to='wiki.chefe')),
                ('npcs', models.ManyToManyField(blank=True, to='wiki.npc')),
            ],
        ),
        migrations.CreateModel(
            name='ArteDoFerrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='artes_do_ferrao/')),
                ('efeito', models.TextField()),
                ('localizacao', models.TextField()),
                ('mestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.npc')),
            ],
        ),
    ]
