# Generated by Django 5.2.4 on 2025-07-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InimigoComum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('regiao', models.TextField()),
                ('dificuldade', models.TextField()),
                ('drop_em_geos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MiniChefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='minichefes/')),
                ('local', models.TextField()),
                ('dica', models.TextField()),
                ('recompensa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='skills/')),
                ('efeito', models.TextField()),
                ('localizacao', models.TextField()),
                ('observacao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='exploracao',
            name='img',
            field=models.ImageField(blank=True, upload_to='exploração/'),
        ),
    ]
