# Generated by Django 5.2.3 on 2025-08-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_inimigocomum_minichefe_skill_exploracao_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploracao',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
