# Generated by Django 5.2.3 on 2025-08-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_exploracao_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploracao',
            name='especial',
            field=models.BooleanField(default=False),
        ),
    ]
